project:
  type: website
  output-dir: docs

website:
  title: "Steven Cheun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects and Publications
      - href: media\Academic_Resume_SC.pdf
        text: Resume

format:
  html:
    theme: flatly
    toc: true

editor: visual

execute:
  freeze: auto

